spring:
  datasource:
    url: jdbc:mysql://localhost:3306/project2023
    username: root
    password: tecsup
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: mysql
    database-platform: org.hibernate.dialect.MySQL57Dialect

  servlet:
    multipart:
      max-request-size: 2MB
      max-file-size: 2MB
      enabled: true

